### ISSUE TITLE
What Version?

### ISSUE THREAD

**Issue by DiBaDu** [cydolo/TSC-Beta#1]
Hey I tested the TeamSpeak 3 Server 3.7.0 Beta crasher. Great works and special thanks to you! But What Server versions i can crash with it? only 3.7.0? Or lower than that? 3.6.1 Is not working. Could i run it on my windows pc or did i have to use a windows server? Maybe the crasher.exe brokes my windows or something like that?

**Comment by cydolo** [comment]
The crasher works on 3.6.1 as well. you have to enter the server address or nickname
Crasher has been fixed in version 3.7.0 Beta 1.
